version: 0.2

env:
  git-credential-helper: yes
  shell: bash

phases:
  pre_build:
    commands:
      - echo Deploying Airflow DAG structure on `date`
      - aws --version; python -V; virtualenv --version
      - ENV=$(aws ssm get-parameters --names /common-services/aws_account_name --query "Parameters[*].{Value:Value}" --output text | cut -d, -f1| tr -d [)
      - echo Working in ${ENV} environment
      - echo Installing libraries
      - pip install apache-airflow==2.2.2
  build:
    commands:
      - echo Updating PYTHONPATH and Building DYNAMIC DAGS for CWR
      - export PYTHONPATH=$PWD/dags/
      - python dags/etl/dynamic_dags_builder/cwr/cwr_big_dag_builder.py ${ENV}

      - echo "Deploying '.airflowignore' and the 'dags/etl/' folder. WARNING! All data in the folder will be updated"
      - aws s3 cp dags/.airflowignore s3://vm-data-provisioning-${ENV}/airflow/dags/
      - aws s3 cp ./requirements.txt s3://vm-data-provisioning-${ENV}/airflow/requirements/
      - aws s3 sync dags/etl/ s3://vm-data-provisioning-${ENV}/airflow/dags/etl/ --delete --request-payer requester --exclude "*__pycache__*" --exclude "*testing_dags*"
